apiVersion: v1
kind: Pod
metadata:
  name: time-nginx
  namespace: loki
spec:
  containers:
  - name: time-nginx
    image: nginx
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
